on:
  push:
    branches:
      - main

name: Deploy to AWS Lambda

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Set up Terraform 1.0.8
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile ci
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile ci

      - name: Build lambda
        run: make build

      - name: Deploy lambda
        run: make deploy
        env:
          TELEGRAM_BOT_API: ${{ secrets.BOT_API_KEY }}
